# Generated by Django 2.2.7 on 2019-11-11 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tten', '0002_match'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='tea2wkt',
            new_name='firstInningsRun',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team1run',
            new_name='firstInningsWicket',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team1wkt',
            new_name='secondInningsRun',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team2run',
            new_name='secondInningsWicket',
        ),
        migrations.RemoveField(
            model_name='match',
            name='t1b1',
        ),
        migrations.AddField(
            model_name='match',
            name='firstInningsPlayed',
            field=models.CharField(default='0 over', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='matchNo',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='secondInningsPlayed',
            field=models.CharField(default='0 over', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='winnerTeam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='tten.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='winning_status',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='tten.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='tten.Team'),
        ),
    ]
