# Generated by Django 2.2.7 on 2019-11-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tten', '0004_inningsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='inningsdata',
            name='extra',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
