# Generated by Django 2.2.7 on 2019-11-12 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tten', '0005_inningsdata_extra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inningsdata',
            old_name='create_date',
            new_name='match_time',
        ),
    ]
